uzi/accounts/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('',views.profile, name='profile'),
    path('login/',LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',LogoutView.as_view(template_name='accounts/logout.html')),
    path('register/',views.register,name = 'register'),
    path('profile/',views.profile, name='profile'),
    path('profile/edit/',views.edit_profile,name='edit_profile'),
    path('change-password/',views.change_password,name='change_password'),    
]

uzi/uzi/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.login_redirect, name="login_redirect"),
    path('admin/', admin.site.urls),
    path('account/',include('accounts.urls')),
    path('about/',views.about,name="about"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uzi/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=50,default='')
    website = models.URLField(default='')
    image = models.ImageField(upload_to='accounts/',default='accounts/user.png',blank = True)
    def __str__(self):
        return self.user.username
        
#creating the userprofile for the superusers
def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.get_or_create( user=kwargs['instance'])

post_save.connect( create_profile ,sender=User)

uzi/accounts/forms.py
from django import forms
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from .models import *

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )
    def save(self, commit=True):
    #commit save the data into database if its true
        user = super(RegistrationForm,self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        if commit:
            user.save()

class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
        )

class ProfileUpdateForm(forms.ModelForm):
    image = forms.ImageField()
    class Meta:
        model = UserProfile
        fields = (
            'description',
            'website',
            'city',
            'image',
        )

uzi/accounts/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.contrib.auth.forms import UserCreationForm,PasswordChangeForm
from accounts.forms import RegistrationForm,UserUpdateForm,ProfileUpdateForm
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
# Create your views here.


def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/account/')
    else:
        form = RegistrationForm()
    return render(request,'accounts/reg_form.html',{'form': form})

@login_required
def profile(request):
    args = {'user': request.user}
    return render(request,'accounts/profile.html', args)

@login_required
def edit_profile(request):
    if request.method == "POST":
        form = UserUpdateForm(request.POST,instance=request.user)
        form_user = ProfileUpdateForm(request.POST,\
                                    request.FILES,\
                                    instance = request.user.userprofile)
        if form.is_valid() and form_user.is_valid:
            form.save()
            form_user.save()
            return redirect('/account/')
    else:
        form = UserUpdateForm(instance=request.user)
        form_user = ProfileUpdateForm(instance = request.user.userprofile)
    args = {'form': form,'form_user': form_user}
    return render(request,'accounts/edit_profile.html',args)

@login_required   
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(data=request.POST,user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/account/profile/')
        else:
            return redirect('/account/change-password/')
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request,'accounts/change_password.html',args)  

def test_view(request):
    return render(request,'accounts/base.html')
# Create your views here.

uzi/uzi/views.py
from django.shortcuts import redirect
from django.shortcuts import render,HttpResponse,redirect 

def login_redirect(request):
    return redirect('/account/profile')

def about(request):
    return render(request,'accounts/about.html')

uzi/accounts/templates/accounts/about.html
{% extends 'base.html' %}

{% block head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<title>
  About
</title>
{% endblock %}



{% block body %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/about-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>About Me</h1>
            <span class="subheading">This is what I do.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
      </div>
    </div>
  </div>

  <hr>
  <script>
      $(document).ready( function () {
          $("#header").remove();;
});
  </script>
{% endblock %}

uzi/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block head %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    {% load static %}
    <style>
                    :root {
                --input-padding-x: 1.5rem;
                --input-padding-y: .75rem;
            }
            
            body {
                background: #212529;
                background: linear-gradient(to right, #24282c, rgb(116, 125, 131));
            }
            
            .card-signin {
                border: 0;
                border-radius: 1rem;
                box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
            }
            
            .card-signin .card-title {
                margin-bottom: 2rem;
                font-weight: 300;
                font-size: 1.5rem;
            }
            
            .card-signin .card-body {
                padding: 2rem;
            }
            
            .form-signin {
                width: 100%;
            }
            
            .form-signin .btn {
                font-size: 80%;
                border-radius: 5rem;
                letter-spacing: .1rem;
                font-weight: bold;
                padding: 1rem;
                transition: all 0.2s;
            }
            
            .form-label-group {
                position: relative;
                margin-bottom: 1rem;
            }
            
            .form-label-group input {
                height: auto;
                border-radius: 2rem;
            }
            
            .form-label-group>input,
            .form-label-group>label {
                padding: var(--input-padding-y) var(--input-padding-x);
            }
            
            .form-label-group>label {
                position: absolute;
                top: 0;
                left: 0;
                display: block;
                width: 100%;
                margin-bottom: 0;
                /* Override default `<label>` margin */
                line-height: 1.5;
                color: #495057;
                border: 1px solid transparent;
                border-radius: .25rem;
                transition: all .1s ease-in-out;
            }
            
            .form-label-group input::-webkit-input-placeholder {
                color: transparent;
            }
            
            .form-label-group input:-ms-input-placeholder {
                color: transparent;
            }
            
            .form-label-group input::-ms-input-placeholder {
                color: transparent;
            }
            
            .form-label-group input::-moz-placeholder {
                color: transparent;
            }
            
            .form-label-group input::placeholder {
                color: transparent;
            }
            
            .form-label-group input:not(:placeholder-shown) {
                padding-top: calc(var(--input-padding-y) + var(--input-padding-y) * (2 / 3));
                padding-bottom: calc(var(--input-padding-y) / 3);
            }
            
            .form-label-group input:not(:placeholder-shown)~label {
                padding-top: calc(var(--input-padding-y) / 3);
                padding-bottom: calc(var(--input-padding-y) / 3);
                font-size: 12px;
                color: #777;
            }
            
            .btn-google {
                color: white;
                background-color: #ea4335;
            }
            
            .btn-facebook {
                color: white;
                background-color: #3b5998;
            }
            
            /* Fallback for Edge
            -------------------------------------------------- */
            
            @supports (-ms-ime-align: auto) {
                .form-label-group>label {
                display: none;
                }
                .form-label-group input::-ms-input-placeholder {
                color: #777;
                }
            }
            
            /* Fallback for IE
            -------------------------------------------------- */
            
            @media all and (-ms-high-contrast: none),
            (-ms-high-contrast: active) {
                .form-label-group>label {
                display: none;
                }
                .form-label-group input:-ms-input-placeholder {
                color: #777;
                }
            }
    </style>>
{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
            <div class="card-body">
                <h5 class="card-title text-center">Change Password</h5>
                <form method="post" class="form-signin">
                        {% csrf_token %}
                <div class="form-label-group">
                    <input type="password" id="old_password" class="form-control" placeholder="Old Password" required>
                    <label for="old_password">Old Password</label>
                </div>
                <br>
                <div class="form-label-group">
                    <input type="password" id="new_password1" class="form-control" placeholder="New Password" required>
                    <label for="new_password1">New Password</label>
                </div>
                <br>
                <div class="form-label-group">
                        <input type="password" id="new_password1" class="form-control" placeholder="Confirm New Password" required>
                        <label for="new_password2">Confirm Password</label>
                    </div>
                    <br>
                <br>
                <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit" style="background-color: #ea4335;">Shoot!</button>
                <hr class="my-4">
                </form>
            </div>
            </div>
        </div>
        </div>
    </div>
    <script>
        $(document).ready( function () {
            $("#header").remove();
});
    </script>
{% endblock %}

uzi/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% block head %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    {% load static %}
    <style>
                    :root {
                --input-padding-x: 1.5rem;
                --input-padding-y: .75rem;
            }
            
            body {
                background: #212529;
                background: linear-gradient(to right, #24282c, rgb(116, 125, 131));
            }
            
            .card-signin {
                border: 0;
                border-radius: 1rem;
                box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
            }
            
            .card-signin .card-title {
                margin-bottom: 2rem;
                font-weight: 300;
                font-size: 1.5rem;
            }
            
            .card-signin .card-body {
                padding: 2rem;
            }
            
            .form-signin {
                width: 100%;
            }
            
            .form-signin .btn {
                font-size: 80%;
                border-radius: 5rem;
                letter-spacing: .1rem;
                font-weight: bold;
                padding: 1rem;
                transition: all 0.2s;
            }
            
            .form-label-group {
                position: relative;
                margin-bottom: 1rem;
            }
            
            .form-label-group input {
                height: auto;
                border-radius: 2rem;
            }
            
            .form-label-group>input,
            .form-label-group>label {
                padding: var(--input-padding-y) var(--input-padding-x);
            }
            
            .form-label-group>label {
                position: absolute;
                top: 0;
                left: 0;
                display: block;
                width: 100%;
                margin-bottom: 0;
                /* Override default `<label>` margin */
                line-height: 1.5;
                color: #495057;
                border: 1px solid transparent;
                border-radius: .25rem;
                transition: all .1s ease-in-out;
            }
            
            .form-label-group input::-webkit-input-placeholder {
                color: transparent;
            }
            
            .form-label-group input:-ms-input-placeholder {
                color: transparent;
            }
            
            .form-label-group input::-ms-input-placeholder {
                color: transparent;
            }
            
            .form-label-group input::-moz-placeholder {
                color: transparent;
            }
            
            .form-label-group input::placeholder {
                color: transparent;
            }
            
            .form-label-group input:not(:placeholder-shown) {
                padding-top: calc(var(--input-padding-y) + var(--input-padding-y) * (2 / 3));
                padding-bottom: calc(var(--input-padding-y) / 3);
            }
            
            .form-label-group input:not(:placeholder-shown)~label {
                padding-top: calc(var(--input-padding-y) / 3);
                padding-bottom: calc(var(--input-padding-y) / 3);
                font-size: 12px;
                color: #777;
            }
            
            .btn-google {
                color: white;
                background-color: #ea4335;
            }
            
            .btn-facebook {
                color: white;
                background-color: #3b5998;
            }
            
            /* Fallback for Edge
            -------------------------------------------------- */
            
            @supports (-ms-ime-align: auto) {
                .form-label-group>label {
                display: none;
                }
                .form-label-group input::-ms-input-placeholder {
                color: #777;
                }
            }
            
            /* Fallback for IE
            -------------------------------------------------- */
            
            @media all and (-ms-high-contrast: none),
            (-ms-high-contrast: active) {
                .form-label-group>label {
                display: none;
                }
                .form-label-group input:-ms-input-placeholder {
                color: #777;
                }
            }
    </style>>
{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
            <div class="card-body">
                <h5 class="card-title text-center">Edit Profile</h5>
                <form method="post" class="form-signin" enctype="multipart/form-data">
                    {% csrf_token %}
                <!-- <input type="text" name="username" class="form-control" autofocus="" required="" id="id_username">  
                <input type="password" name="first_name" required="" class="form-control" id="id_first_name">  
                <input type="password" name="last_name" required="" class="form-control" id="id_last_name">
                <input type="password" name="password1" required="" class="form-control" id="id_password"> 
                <input type="password" name="password2" required="" class="form-control" id="id_password">-->
                    <div class="form-label-group">
                        <input type="text" name="first_name" maxlength="30" class="form-control" placeholder="{{ form.first_name }}" id="id_first_name" >                    
                        <label for="id_first_name">First Name</label>
                    </div>
                    <div class="form-label-group">
                        <input type="text" name="last_name" maxlength="150" class="form-control" placeholder="{{ form.last_name }}" id="id_last_name">                    
                        <label for="id_last_name">Last Name</label>
                    </div>
                    <div class="form-label-group">
                        <input type="email" name="email" maxlength="100" required="" class="form-control" placeholder="{{ form.email }}" id="id_email">                    
                        <label for="id_email">Description</label>
                    </div>
                    <div class="form-label-group">
                        <input type="text" name="description" maxlength="100" required="" class="form-control" placeholder="{{ form_user.description }}" id="id_description">                    
                        <label for="id_email">Description</label>
                    </div>
                    <div class="form-label-group">
                        <input type="url" name="website" maxlength="200" required="" class="form-control" placeholder="{{ form_user.website }}" id="id_website">                    
                        <label for="id_website">Website</label>
                    </div>
                    <div class="form-label-group">
                      <input type="text" name="city" maxlength="50" required="" class="form-control"placeholder="{{ form_user.city }}" id="id_city">                    
                        <label for="id_city">City</label>
                    </div>
                    <div class="form-group">
                      <label for="id_image">Image</label>
                      <input type="file" name="image" accept="image/*" class="form-control" id="id_image">                    
                      
                    </div>
                    <br>
                    <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit" style="background-color: #ea4335;">Shoot!</button>
                    <hr class="my-4">
                </form>
            </div>
            </div>
        </div>
        </div>
    </div>
    <script>
        $(document).ready( function () {
            $("#header").remove();
});
    </script>
{% endblock %}

               

uzi/accounts/templates/accounts/logout.html
{% extends 'base.html' %}
<!DOCTYPE html>
{% block body%}
<div class="container">
    <h1>
        You have logged out
    </h1>
</div>    
{% endblock %}    

uzi/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
<style>
.card{ 
    margin: 0 auto;
}
.prof{
    text-align: center;
    display: inline;
}
</style>
{% endblock %}

{% block body %}
<div class="card border-dark mb3" style="width: 25em;">
        <div class="card-header" style="background-color:black;color:white"><h1 style="text-align:center">Profile</h1></div>
        <br>
        <div class="prof" style="padding:20px">
        {% if user.userprofile.image %}
          <img src="{{ user.userprofile.image.url }}" width="280px">
        {% endif %}
        <br>
        <br>
        <p>Username:{{ user.username }}</p>
        <p>First Name: {{ user.first_name }}</p>
        <p>Last Name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Desciption: {{ user.userprofile.description }}</p>
        <p>Phone: {{ user.userprofile.phone }}</p>
        <p>Website: {{ user.userprofile.website }}</p>
        <p>City: {{ user.userprofile.city }}</p>
        </div>
{% endblock %}

uzi/accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}
{% block head %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    {% load static %}
    <style>
                    :root {
                --input-padding-x: 1.5rem;
                --input-padding-y: .75rem;
            }
            
            body {
                background: #212529;
                background: linear-gradient(to right, #24282c, rgb(116, 125, 131));
            }
            
            .card-signin {
                border: 0;
                border-radius: 1rem;
                box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
            }
            
            .card-signin .card-title {
                margin-bottom: 2rem;
                font-weight: 300;
                font-size: 1.5rem;
            }
            
            .card-signin .card-body {
                padding: 2rem;
            }
            
            .form-signin {
                width: 100%;
            }
            
            .form-signin .btn {
                font-size: 80%;
                border-radius: 5rem;
                letter-spacing: .1rem;
                font-weight: bold;
                padding: 1rem;
                transition: all 0.2s;
            }
            
            .form-label-group {
                position: relative;
                margin-bottom: 1rem;
            }
            
            .form-label-group input {
                height: auto;
                border-radius: 2rem;
            }
            
            .form-label-group>input,
            .form-label-group>label {
                padding: var(--input-padding-y) var(--input-padding-x);
            }
            
            .form-label-group>label {
                position: absolute;
                top: 0;
                left: 0;
                display: block;
                width: 100%;
                margin-bottom: 0;
                /* Override default `<label>` margin */
                line-height: 1.5;
                color: #495057;
                border: 1px solid transparent;
                border-radius: .25rem;
                transition: all .1s ease-in-out;
            }
            
            .form-label-group input::-webkit-input-placeholder {
                color: transparent;
            }
            
            .form-label-group input:-ms-input-placeholder {
                color: transparent;
            }
            
            .form-label-group input::-ms-input-placeholder {
                color: transparent;
            }
            
            .form-label-group input::-moz-placeholder {
                color: transparent;
            }
            
            .form-label-group input::placeholder {
                color: transparent;
            }
            
            .form-label-group input:not(:placeholder-shown) {
                padding-top: calc(var(--input-padding-y) + var(--input-padding-y) * (2 / 3));
                padding-bottom: calc(var(--input-padding-y) / 3);
            }
            
            .form-label-group input:not(:placeholder-shown)~label {
                padding-top: calc(var(--input-padding-y) / 3);
                padding-bottom: calc(var(--input-padding-y) / 3);
                font-size: 12px;
                color: #777;
            }
            
            .btn-google {
                color: white;
                background-color: #ea4335;
            }
            
            .btn-facebook {
                color: white;
                background-color: #3b5998;
            }
            
            /* Fallback for Edge
            -------------------------------------------------- */
            
            @supports (-ms-ime-align: auto) {
                .form-label-group>label {
                display: none;
                }
                .form-label-group input::-ms-input-placeholder {
                color: #777;
                }
            }
            
            /* Fallback for IE
            -------------------------------------------------- */
            
            @media all and (-ms-high-contrast: none),
            (-ms-high-contrast: active) {
                .form-label-group>label {
                display: none;
                }
                .form-label-group input:-ms-input-placeholder {
                color: #777;
                }
            }
    </style>>
{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
            <div class="card-body">
                <h5 class="card-title text-center">Register</h5>
                <form method="post" class="form-signin">
                        {% csrf_token %}
                <!-- <input type="text" name="username" class="form-control" autofocus="" required="" id="id_username">  
                <input type="password" name="first_name" required="" class="form-control" id="id_first_name">  
                <input type="password" name="last_name" required="" class="form-control" id="id_last_name">
                <input type="password" name="password1" required="" class="form-control" id="id_password"> 
                <input type="password" name="password2" required="" class="form-control" id="id_password">-->
                <div class="form-label-group">
                        <input type="text" name="username" maxlength="150" autofocus="" required="" class="form-control" id="id_username">
                        <label for="id_username">User Name</label>
                    </div>
                    <div class="form-label-group">
                        <input type="text" name="first_name" maxlength="30" class="form-control" id="id_first_name">                    
                        <label for="id_first_name">First Name</label>
                    </div>
                    <div class="form-label-group">
                        <input type="text" name="last_name" maxlength="150" class="form-control" id="id_last_name">                    
                        <label for="id_last_name">Last Name</label>
                    </div>
                    <div class="form-label-group">
                        <input type="email" name="email" class="form-control" required="" id="id_email">                    
                        <label for="id_email">Email address</label>
                      </div>
                    <div class="form-label-group">
                        <input type="password" name="password1" required="" class="form-control" id="id_password1">                    
                        <label for="id_password1">Password</label>
                    </div>
                    <div class="form-label-group">
                        <input type="password" name="password2" required="" class="form-control" id="id_password2">                    
                        <label for="id_password2">Confirm Password</label>
                    </div>
                    <br>
                    <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit" style="background-color: #ea4335;">Shoot!</button>
                    <hr class="my-4">
                </form>
            </div>
            </div>
        </div>
        </div>
    </div>
    <script>
        $(document).ready( function () {
            $("#header").remove();
});
    </script>
{% endblock %}

               